import './globals.css'

export const metadata = {
  title: 'Counter component with persistent state',
  description: 'Generated by create next app',
  keywords: ['nextjs', 'client side', 'state', 'sessionStorage']
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body> {children} </body>
    </html>
  )
}
